// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrM6VJ4i0GcZl6EGrv-FKU6ck3iXDveHs',
    appId: '1:984014356051:web:84a2006c5bbd0cd3add0a6',
    messagingSenderId: '984014356051',
    projectId: 'mall-17759',
    authDomain: 'mall-17759.firebaseapp.com',
    storageBucket: 'mall-17759.appspot.com',
    measurementId: 'G-HZEEDCFX3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4uJB7lPOT7wic1yj4VBhOfL0pbLnNfGQ',
    appId: '1:984014356051:android:f4dba97963d64167add0a6',
    messagingSenderId: '984014356051',
    projectId: 'mall-17759',
    storageBucket: 'mall-17759.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApKOch7iqRHPEMz1EPoaKvMhzBBZ75Qbo',
    appId: '1:984014356051:ios:f2643d5b14d5af3dadd0a6',
    messagingSenderId: '984014356051',
    projectId: 'mall-17759',
    storageBucket: 'mall-17759.appspot.com',
    androidClientId: '984014356051-g4k79v5ec3pj2e146osi2j1h2kilmrfr.apps.googleusercontent.com',
    iosClientId: '984014356051-u0duqk1pp590g8tml1esuc78t4of1nko.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApKOch7iqRHPEMz1EPoaKvMhzBBZ75Qbo',
    appId: '1:984014356051:ios:f2643d5b14d5af3dadd0a6',
    messagingSenderId: '984014356051',
    projectId: 'mall-17759',
    storageBucket: 'mall-17759.appspot.com',
    androidClientId: '984014356051-g4k79v5ec3pj2e146osi2j1h2kilmrfr.apps.googleusercontent.com',
    iosClientId: '984014356051-u0duqk1pp590g8tml1esuc78t4of1nko.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrM6VJ4i0GcZl6EGrv-FKU6ck3iXDveHs',
    appId: '1:984014356051:web:11ff2d65def35134add0a6',
    messagingSenderId: '984014356051',
    projectId: 'mall-17759',
    authDomain: 'mall-17759.firebaseapp.com',
    storageBucket: 'mall-17759.appspot.com',
    measurementId: 'G-4H5Z7R6BFW',
  );

}